trigger:
  branches:
    include:
    - main
    - develop

variables:
- group: TF_PIPELINES
- name: poolName
  value: 'Azure Pipelines'
- name: vmImage
  value: 'ubuntu-latest'
# image related vars
- name: gallery_rg_name
  value: 'dani-resource-group'
- name: gallery_name
  value: 'winGallery'
- name: image_name
  value: 'test-image-1'
- name: image_publisher
  value: 'DanielaBG'
- name: image_offer
  value: 'WindowsServer'
- name: image_sku
  value: 'Example12345'


stages:
- stage: TerraformImg
  displayName: Deploy Terraform for image definition
  pool:
    name: $(poolName)
    vmImage: $(vmImage)

  jobs:
  - job: terraform
    displayName: Terraform provisioning
    workspace:
      clean: all
    steps:
      - checkout: self
      - script: |
          chmod +x scripts/write_img_def_tfvars.sh
          cat terraform.tfvars
        workingDirectory: './image_def'
        displayName: 'Create tfvars file from global variables'
        env:
          gallery_rg_name: $(gallery_rg_name)
          gallery_name: $(gallery_name)
          image_name: $(image_name)
          image_publisher: $(image_publisher)
          image_offer: $(image_offer)
          image_sku: $(image_sku)
      - template: 'templates/terraform_plan_template.yml'
        parameters:
          tfWorkingDir: './image_def'
      - template: 'templates/terraform_apply_template.yml'
        parameters:
          tfWorkingDir: './image_def'
