trigger:
  branches:
    include:
    - main
    - develop

variables:
- group: TF_PIPELINES
- name: poolName
  value: 'Azure Pipelines'
- name: vmImage
  value: 'ubuntu-latest'
# image related vars
- name: TF_VAR_gallery_rg_name
  value: 'dani-resource-group'
- name: TF_VAR_gallery_name
  value: 'winGallery'
- name: TF_VAR_image_name
  value: 'test-image-1'
- name: TF_VAR_image_publisher
  value: 'DanielaBG'
- name: TF_VAR_image_offer
  value: 'WindowsServer'
- name: TF_VAR_image_sku
  value: 'Example12345'


stages:
- stage: TerraformImg
  displayName: Deploy Terraform for image definition
  pool:
    name: $(poolName)
    vmImage: $(vmImage)

  jobs:
  - job: plan
    displayName: Terraform Plan
    workspace:
      clean: all
    steps:
      - template: 'templates/terraform_plan_template.yml'
        parameters:
          tfWorkingDir: './image_def'
  - job: waitForValidation
    displayName: Wait for external validation
    dependsOn: plan
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            danybecerr@gmail.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'reject'
  - job:
    displayName: Terraform Apply
    dependsOn: waitForValidation
    condition: in(dependencies.waitForValidation.result, 'Succeeded', 'Skipped')
    workspace:
      clean: all
    steps:
      - template: 'templates/terraform_apply_template.yml'
        parameters:
          tfWorkingDir: './image_def'
