trigger:
  branches:
    include:
    - main
    - develop

variables:
- group: TF_PIPELINES
- name: poolName
  value: 'Azure Pipelines'
- name: vmImage
  value: 'ubuntu-latest'


stages:
- stage: Terraform
  displayName: Deploy Terraform
  pool:
    name: $(poolName)
    vmImage: $(vmImage)

  jobs:
  - job: plan
    displayName: Terraform Plan
    workspace:
      clean: all
    steps:
      - template: terraform_plan_template.yml
        parameters:
          tfWorkingDir: '$(Pipeline.Workspace)'
  - job: waitForValidation
    displayName: Wait for external validation
    dependsOn: plan
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            danybecerr@gmail.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'reject'
  - job:
    displayName: Terraform Apply
    dependsOn: waitForValidation
    condition: in(dependencies.waitForValidation.result, 'Succeeded', 'Skipped')
    workspace:
      clean: all
    steps:
      - template: terraform_apply_template.yml
        parameters:
          tfWorkingDir: '$(Pipeline.Workspace)'
