- name: Install AZ Cli
  ansible.windows.win_powershell:
    script: |
      $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi

- name: Install Azure Powershell module
  ansible.windows.win_powershell:
    script: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module -Name Az -Scope AllUsers -Repository PSGallery -Force
